


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."categories" (
    "id" "text" NOT NULL,
    "icon" "text" DEFAULT ''::"text" NOT NULL,
    "name_en" "text" DEFAULT ''::"text" NOT NULL,
    "name_fa" "text" DEFAULT ''::"text" NOT NULL,
    "name_fr" "text" DEFAULT ''::"text" NOT NULL,
    "order" smallint DEFAULT '0'::smallint NOT NULL
);


ALTER TABLE "public"."categories" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."hours" (
    "period_en" "text" DEFAULT ''::"text" NOT NULL,
    "period_fa" "text" DEFAULT ''::"text" NOT NULL,
    "period_fr" "text" DEFAULT ''::"text" NOT NULL,
    "time_en" "text" DEFAULT ''::"text" NOT NULL,
    "time_fa" "text" DEFAULT ''::"text" NOT NULL,
    "time_fr" "text" DEFAULT ''::"text" NOT NULL,
    "id" smallint NOT NULL
);


ALTER TABLE "public"."hours" OWNER TO "postgres";


ALTER TABLE "public"."hours" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."hours_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."icons" (
    "path" "text" NOT NULL
);


ALTER TABLE "public"."icons" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."menu_items" (
    "id" integer NOT NULL,
    "category_id" "text",
    "name_en" "text" DEFAULT ''::"text" NOT NULL,
    "name_fa" "text" DEFAULT ''::"text" NOT NULL,
    "name_fr" "text" DEFAULT ''::"text" NOT NULL,
    "price" integer DEFAULT 0 NOT NULL,
    "img" "text" DEFAULT ''::"text" NOT NULL,
    "description_en" "text" DEFAULT ''::"text" NOT NULL,
    "description_fa" "text" DEFAULT ''::"text" NOT NULL,
    "description_fr" "text" DEFAULT ''::"text" NOT NULL,
    "available" boolean DEFAULT true NOT NULL,
    "options" "jsonb"[],
    "order" integer DEFAULT 0 NOT NULL,
    "badges" "jsonb"[]
);


ALTER TABLE "public"."menu_items" OWNER TO "postgres";


ALTER TABLE "public"."menu_items" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."menu_items_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."categories"
    ADD CONSTRAINT "categories_id_key" UNIQUE ("id");



ALTER TABLE ONLY "public"."categories"
    ADD CONSTRAINT "categories_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."hours"
    ADD CONSTRAINT "hours_id_key" UNIQUE ("id");



ALTER TABLE ONLY "public"."hours"
    ADD CONSTRAINT "hours_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."icons"
    ADD CONSTRAINT "icons_pkey" PRIMARY KEY ("path");



ALTER TABLE ONLY "public"."menu_items"
    ADD CONSTRAINT "menu_items_id_key" UNIQUE ("id");



ALTER TABLE ONLY "public"."menu_items"
    ADD CONSTRAINT "menu_items_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."menu_items"
    ADD CONSTRAINT "menu_items_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "public"."categories"("id") ON UPDATE CASCADE ON DELETE SET NULL;



CREATE POLICY "Enable all for authenticated users only" ON "public"."categories" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Enable all for authenticated users only" ON "public"."hours" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Enable all for authenticated users only" ON "public"."icons" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Enable all for authenticated users only" ON "public"."menu_items" TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "Enable read access for all users" ON "public"."categories" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."hours" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."icons" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."menu_items" FOR SELECT USING (true);



ALTER TABLE "public"."categories" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."hours" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."icons" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."menu_items" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";








































































































































































GRANT ALL ON TABLE "public"."categories" TO "anon";
GRANT ALL ON TABLE "public"."categories" TO "authenticated";
GRANT ALL ON TABLE "public"."categories" TO "service_role";



GRANT ALL ON TABLE "public"."hours" TO "anon";
GRANT ALL ON TABLE "public"."hours" TO "authenticated";
GRANT ALL ON TABLE "public"."hours" TO "service_role";



GRANT ALL ON SEQUENCE "public"."hours_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."hours_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."hours_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."icons" TO "anon";
GRANT ALL ON TABLE "public"."icons" TO "authenticated";
GRANT ALL ON TABLE "public"."icons" TO "service_role";



GRANT ALL ON TABLE "public"."menu_items" TO "anon";
GRANT ALL ON TABLE "public"."menu_items" TO "authenticated";
GRANT ALL ON TABLE "public"."menu_items" TO "service_role";



GRANT ALL ON SEQUENCE "public"."menu_items_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."menu_items_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."menu_items_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































